/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.PagoArticulo;
import Datos.BaseDatos;
import Modulos.Alumno;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Poot
 */
public class PagarArticulo extends javax.swing.JFrame
{

    DefaultComboBoxModel<Alumno> modeloAlumnos;
    BaseDatos base;

    /**
     * Creates new form PagarArticulo
     */
    public PagarArticulo()
    {

        modeloAlumnos = new DefaultComboBoxModel<Alumno>();
        base = new BaseDatos();
        cargarModeloAlum();
        initComponents();
    }

    private void cargarModeloAlum()
    {
        ArrayList<Alumno> listaAlumnos;
        listaAlumnos = base.obtenerAlumnos();

        for (Alumno alumnos : listaAlumnos)
            modeloAlumnos.addElement(alumnos);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIDArticulo = new javax.swing.JLabel();
        PrecioArticuloPA = new javax.swing.JLabel();
        NumArticuloPA = new javax.swing.JLabel();
        txtIDArticulo = new javax.swing.JTextField();
        txtPrecioArticulo = new javax.swing.JTextField();
        txtNumeroArticulos = new javax.swing.JTextField();
        TituloPagoArticulo = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        PrimerPagoPA = new javax.swing.JLabel();
        BtGuardarPagoA = new javax.swing.JButton();
        BtRegresarPagoA = new javax.swing.JButton();
        AlumnoPA = new javax.swing.JLabel();
        comboAlumnos = new javax.swing.JComboBox<>();
        lblNombreArticulo = new javax.swing.JLabel();
        txtNombreArticulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIDArticulo.setText("ID Articulo : ");

        PrecioArticuloPA.setText("Precio del Articulo : ");

        NumArticuloPA.setText("Numero de Articulos : ");

        txtIDArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDArticuloActionPerformed(evt);
            }
        });

        txtPrecioArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioArticuloActionPerformed(evt);
            }
        });

        txtNumeroArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroArticulosActionPerformed(evt);
            }
        });

        TituloPagoArticulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        TituloPagoArticulo.setText("Pago de Articulo");

        PrimerPagoPA.setText("Pago : ");

        BtGuardarPagoA.setText("Guardar");
        BtGuardarPagoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtGuardarPagoAMouseClicked(evt);
            }
        });
        BtGuardarPagoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarPagoAActionPerformed(evt);
            }
        });

        BtRegresarPagoA.setText("Regresar");

        AlumnoPA.setText("Alumno :");

        comboAlumnos.setModel(modeloAlumnos);
        comboAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlumnosActionPerformed(evt);
            }
        });

        lblNombreArticulo.setText("Nombre del Articulo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumArticuloPA)
                            .addComponent(AlumnoPA)
                            .addComponent(lblIDArticulo)
                            .addComponent(lblNombreArticulo)
                            .addComponent(PrecioArticuloPA)
                            .addComponent(PrimerPagoPA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroArticulos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioArticulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreArticulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDArticulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAlumnos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(TituloPagoArticulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtRegresarPagoA, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(BtGuardarPagoA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(TituloPagoArticulo)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlumnoPA))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDArticulo)
                    .addComponent(txtIDArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreArticulo)
                    .addComponent(txtNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrecioArticuloPA)
                    .addComponent(txtPrecioArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumArticuloPA)
                    .addComponent(txtNumeroArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PrimerPagoPA)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtRegresarPagoA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtGuardarPagoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(107, 107, 107))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDArticuloActionPerformed

    private void txtPrecioArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioArticuloActionPerformed

    private void txtNumeroArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroArticulosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroArticulosActionPerformed

    private void comboAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlumnosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAlumnosActionPerformed

    private void BtGuardarPagoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtGuardarPagoAMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_BtGuardarPagoAMouseClicked

    private void BtGuardarPagoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarPagoAActionPerformed
        Alumno alum = (Alumno) comboAlumnos.getSelectedItem();
        int idArticulo = Integer.parseInt(txtIDArticulo.getText());
        String nombreArticulo = txtNombreArticulo.getText();
        double precioArticulo = Double.parseDouble(txtPrecioArticulo.getText());
        double numeroArticulos = Double.parseDouble(txtNumeroArticulos.getText());
        double pago = Double.parseDouble(txtPago.getText());

        PagoArticulo pagoArticulo = new PagoArticulo(idArticulo, nombreArticulo, precioArticulo,
                numeroArticulos, pago, alum.getID());
        JOptionPane.showMessageDialog(this, "Producto pagado correctamente");
        base.insertarPagoArticulo(pagoArticulo);
    }//GEN-LAST:event_BtGuardarPagoAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PagarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PagarArticulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlumnoPA;
    private javax.swing.JButton BtGuardarPagoA;
    private javax.swing.JButton BtRegresarPagoA;
    private javax.swing.JLabel NumArticuloPA;
    private javax.swing.JLabel PrecioArticuloPA;
    private javax.swing.JLabel PrimerPagoPA;
    private javax.swing.JLabel TituloPagoArticulo;
    private javax.swing.JComboBox<Alumno> comboAlumnos;
    private javax.swing.JLabel lblIDArticulo;
    private javax.swing.JLabel lblNombreArticulo;
    private javax.swing.JTextField txtIDArticulo;
    private javax.swing.JTextField txtNombreArticulo;
    private javax.swing.JTextField txtNumeroArticulos;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtPrecioArticulo;
    // End of variables declaration//GEN-END:variables
}
